### ISSUE TITLE
Crashing on Brooklyn Bank [With Crashlog]

### ISSUE THREAD

**Issue by Chibibowa** [Ellieeeee/Heist-Weather-Changer#2]
As of today, 08 july 2020.

This is the only map to my knowledge where I crash on. Here is the full crashlog. I was running bare metal with only these "mods":

Base (BLT)
Beardlib
CreateEmptyLobby
downloads
Heist Weather Changer (latest version, freshly downloaded, not even configured)
logs
rebuy contract
saves (with nothing in it)
pd2-hoplib-master

---

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlGetNtGlobalFlags                                 
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                  spawn_unit()  lib/units/props/managespawnedunits.lua:50           
         spawn_and_link_unit()  lib/units/props/managespawnedunits.lua:133          
  set_character_visual_state()  lib/managers/criminalsmanager.lua:548               
update_character_visual_state()  @mods/Heist                                         
                                Weather                                             
Changer/Hooks/criminalsmanager.lua:62  update_character_visual_state()                     
lib/network/base/networkpeer.lua:2399  set_unit()                                          
lib/network/base/networkpeer.lua:2363  spawn_unit()                                        
lib/network/base/networkpeer.lua:2241  spawn_players()                                     
lib/network/base/basenetworksession.lua:1513  update()                                            
lib/states/ingamewaitingforplayers.lua:291  update()                                            
core/lib/utils/game_state_machine/coregamestatemachine.lua:92  original()                                          
      lib/setups/setup.lua:880  update()                                            
@mods/base/req/core/Hooks.lua:185  update()                                            
  lib/setups/gamesetup.lua:718  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:557  
-------------------------------

System information:
	Application version : 1.95.896
	CPU : Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon VII / aticfx32.dll[26.20.15029.27016]
	Language : english
	Memory :     16296MB 128KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Realtek Digital Output(Optical) (Realtek High Definition Audio))

**Comment by Ellieeeee** [comment]
resolved
